# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    restart: always
#    volumes:
#      - ./pgdata:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: moviedb
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
